### ISSUE TITLE
Development branch is missing

### ISSUE THREAD

**Issue by patrick-ve** [lennartdeknikker/MeetMe#11]
As of this moment we have 2 branches:

> master
> 5-deploy-on-heroku

Obviously this implies that everything that we are doing on branch `5-deploy-on-heroku` is for development purposes regarding issue #5. However we are all working on different issues, therefore we require multiple branches that we will be working on. 

The desired workflow is as following:
1. Create a `development` branch that is an exact copy of the most stable release of the `master` branch. 
2. From this `development` branch, everybody forks off to a feature branch that comprises a specific issue, i.e. `9-add-progressive-disclosure`. 
3. You will work on this feature branch, until the feature has been finished.
4. When the feature has been finished, you should create a pull request.
5. Everybody will review the code that has been submitted, and when the code passes the reviews successfully, we can merge that specific feature branch into the `development` branch. 
6. It is possible that this causes merge conflicts, which should be solved by the author of the feature.
7. When we are happy with the state of the `development` branch, we can merge `develop` with `master`, and push a new deployment on Heroku.

**Comment by lennartdeknikker** [comment]
I added a new branch for development purposes as described.
